### ISSUE TITLE
Fix crashing issues

### ISSUE THREAD

**Issue by slmnio** [slmnio/slmngg-sfc#148]
There's an issue that has been plaguing the server for a while. Something is throwing an error while interfacing with Discord which throws an error which restarts the server. It seems to be triggering the most during broadcasts, and might be related to player cams.

This is the stack trace, and there's nothing that links it back to the SLMN.GG code which makes finding the error hrad.

> TypeError: Cannot read properties of undefined (reading 'cache')
    at MessageCreateAction.handle (/var/js/slmngg-sfc/server/node_modules/discord.js/src/client/actions/MessageCreate.js:13:41)
    at Object.module.exports [as MESSAGE_CREATE] (/var/js/slmngg-sfc/server/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/var/js/slmngg-sfc/server/node_modules/discord.js/src/client/websocket/WebSocketManager.js:345:31)
    at WebSocketShard.onPacket (/var/js/slmngg-sfc/server/node_modules/discord.js/src/client/websocket/WebSocketShard.js:443:22)
    at WebSocketShard.onMessage (/var/js/slmngg-sfc/server/node_modules/discord.js/src/client/websocket/WebSocketShard.js:300:10)
    at WebSocket.onMessage (/var/js/slmngg-sfc/server/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (node:events:394:28)
    at Receiver.receiverOnMessage (/var/js/slmngg-sfc/server/node_modules/ws/lib/websocket.js:970:20)
    at Receiver.emit (node:events:394:28)
    at Receiver.dataMessage (/var/js/slmngg-sfc/server/node_modules/ws/lib/receiver.js:517:14)

**Comment by slmnio** [comment]
I've updated the SLMN.GG server PM2 process to use [extended stack traces](https://stackoverflow.com/a/13155846) to see if it shows anything else. It might struggle if it's an event fired by discord.js and not something that the SLMN.GG code triggers, but it might help track something down.
